### PR TITLE
Replace default blocking spi Write implementation with an optimized one

### PR DESCRIPTION
**Pull request by timbod7**

### CODE REVIEW

**Comment by TheZoq2** [comment]
Sorry for the delay in reviewing this. The change looks great, would you mind also adding an entry to `CHANGELOG.md`?

**Comment by burrbull** [comment]
Need rebase.

**Comment by timbod7** [comment]
Updated:
    - rebased on master
    - added changelog entry

**Comment by TheZoq2** [comment]
Lovely, thanks!

**Pull request merged**
