### PR TITLE
Add example of GPIO input mode

### PR DESCRIPTION
**Pull request by YuaXan**
I not found example about gpio input mode long time, so I written the example to share everyone.

### CODE REVIEW

**Comment by YuaXan** [comment]
Not guys come pull requests? @TheZoq2 @therealprof

**Comment by therealprof** [comment]
@YuaXan Thanks for the PR! I think we could certainly use more examples. There're some things which need improving though to make it an educational resource:

- [ ] More code comments
- [ ] Spellcheck
- [ ] Addition to the Cargo.toml

Also the manual re-implementation of the `OutputPin` (and other) traits is a bit unusual. Why not use type aliases instead to define your custom `RedLedPin` and `GreenLedPin`?

**Comment by YuaXan** [comment]
@therealprof Thanks for your tell me about my mistakes. I fixed these mistakes.

**Review by burrbull — APPROVED** [review]

**Comment by YuaXan** [comment]
@burrbull Thanks for merged my PR, This was my first contribution to opensource. I wish I  will keep going. :D

**Comment by TheZoq2** [comment]
@YuaXan nice job on your first contribution! Sorry for ignoring this (and a bunch of other PRs) for so long, I hope that didn't put you off too much!

And thanks @burrbull for taking care of all the PRs which i have ignored :heart:

**Pull request merged**
