### PR TITLE
rcc config

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by TheZoq2** [comment]
Nice, this seems like an excellent change. I'll try to find the time to give it a proper review soon

**Review by TeXitoi — APPROVED** [review]
Oh, great, we could even add unit test to check we do the good autoconfiguration!

**Comment by TeXitoi** [comment]
@burrbull did you use this branch on some of your project, on real hardware? If yes, I'm OK to merge it.

**Comment by burrbull** [comment]
> @burrbull did you use this branch on some of your project, on real hardware? If yes, I'm OK to merge it.

I would rather have someone else recheck this.

**Comment by jasLogic** [comment]
Everything seems to work fine but I only really tested if my changes still function properly.

**Pull request merged**
