### PR TITLE
SCK, MISO, MOSI

### PR DESCRIPTION
**Pull request by burrbull**
Use only this sequence.

Related to #339.
Need decision. What we need more? Possibility to pass pins in custom sequence or more simple API.
cc @TheZoq2 @therealprof @TeXitoi @adamgreig @thalesfragoso

### CODE REVIEW

**Comment by burrbull** [comment]
Also we could add advanced trait
```rust
pub trait SpiExt<SPI> {}

impl<SPI, REMAP, PINS> SpiExt<SPI> for Spi<SPI1, REMAP, PINS, u8>
where
    REMAP: Remap<Periph = SPI>,
    PINS: Pins<REMAP>,
{
}
```
that would let write just
```rust
fn setup() -> (impl SpiExt<SPI1>, PA4<Output<PushPull>>) {
```
But this is rare needed case.

**Review by TeXitoi — APPROVED** [review]

**Comment by TeXitoi** [comment]
I'm fine with removing the free order agrument.

**Comment by pdgilbert** [comment]
FWIW, the PR is working (using `Spi<SPI1, Spi1NoRemap, impl Pins<Spi1NoRemap>, u8>,`) in my testing too.

**Comment by burrbull** [comment]
bors r=TeXitoi

**Comment by TeXitoi** [comment]
I think there is no bors here.

**Comment by burrbull** [comment]
> I think there is no bors here.

Do you have permissions for manual merge?

**Comment by TeXitoi** [comment]
Yes, that's a long time I didn't to it here. rebase and merge?

**Comment by TeXitoi** [comment]
Looks more like squash and merge here.

**Comment by burrbull** [comment]
> Yes, that's a long time I didn't to it here. rebase and merge?

Just merge.

Could we add bors?

**Comment by TeXitoi** [comment]
I have nothing against that. @TheZoq2 ?

**Comment by TheZoq2** [comment]
Looks like I'm late, but I have nothing against that. I'll have to learn how to use it, but that should be no problem :)

Re: merge/rebase/squash, I like to keep a linear history so I tend to squash PRs with small changes and many random commits, and rebase the rest.

**Pull request merged**
