### PR TITLE
Rework examples to apply to more targets and test in CI

### PR DESCRIPTION
**Pull request by therealprof**
This also improves the required-features selection for the examples.

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by burrbull** [comment]
`bors` does not manage this repository.

We should fix this.

**Comment by therealprof** [comment]
> bors does not manage this repository.
> We should fix this.

We could, however there's very little benefit for small teams and even worse it has it's own set of funny issues.

**Comment by TheZoq2** [comment]
Sorry for the delay! Looks like some good changes :)

**Pull request merged**
