### PR TITLE
alternative implementation for SPI pins

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by therealprof** [comment]
Looks good.

**Comment by burrbull** [comment]
What is better?
```rust
let spi = dp.SPI2.spi(
        (spi::NoSck, spi::NoMiso, gpioa.pa10),
...
```
or 
```rust
let spi = dp.SPI2.spi(
        (gpio::NoPin, gpio::NoPin, gpioa.pa10),
...
```

**Comment by therealprof** [comment]
```
let spi = dp.SPI2.spi(
        (spi::NoSck, spi::NoMiso, gpioa.pa10),
```

Is better. It expresses intent and thus prevents misconfiguration.

**Comment by burrbull** [comment]
Ok.

But misconfiguration is not possible in second variant too.

**Comment by therealprof** [comment]
> But misconfiguration is not possible in second variant too.

Well, misconfiguration in the sense of the user accidentally opting out of the wrong thing. If you read `NoPin` you know that you're not using a pin but which one. If you only allow `NoMiso` then everyone can see on a first glance that you're not using a physical MISO pin.

**Comment by TheZoq2** [comment]
I agree that `NoMiso/NoMosi` is better than `NoPin`.

I would almost like to change it to `SpiPins{miso, mosi, sck}` for even more clarity. I find myself always having to look up the ordering of the pins when using SPI. That is more verbose though, so we should probably allow both.

Perhaps we could add `Impl<Into>

**Comment by TheZoq2** [comment]
Looks good in its current state, we can probably do the thing I mentioned in the previous comment later.

**Comment by burrbull** [comment]
In last commit I've implemented `Pins` trait for different order.
Now you can pass `(sck, miso, mosi)` or `(mosi, miso, sck)` or `(mosi, NoMiso, NoSck)`, etc.

**Comment by TheZoq2** [comment]
Looks good, thanks!

**Pull request merged**
