### PR TITLE
ccmrX_input

### PR DESCRIPTION
**Pull request by burrbull**
This workaround adds input() method to ccmr1_output for access to ccmr1_input.
Depends on https://github.com/stm32-rs/stm32-rs/pull/223

@gbip, can you test this?

### CODE REVIEW

**Comment by gbip** [comment]
I am not available until next tuesday to test this.

**Comment by therealprof** [comment]
Also it doesn't compile at the moment, is there a newer stm32-rs required?

**Comment by burrbull** [comment]
Yes, waiting for stm32-rs.

**Comment by TeXitoi** [comment]
Nothing new here?

**Comment by burrbull** [comment]
Required code is already in `stm32-rs` master. Waiting for release.

**Comment by burrbull** [comment]
Close in favour of #88 .

**Pull request closed without merging**
