### PR TITLE
Copy memory.x to output folder

### PR DESCRIPTION
**Pull request by jaysonsantos**
This makes projects like defmt work out of the box.

Is this worth it to add to the changelog?

### CODE REVIEW

**Comment by thalesfragoso** [comment]
This crate has support for several different microcontrollers with different flash and ram sizes, so I'm not sure if this is a good idea.

**Comment by jaysonsantos** [comment]
Hey there, what if the `build.rs` chooses the memory.x for the specific feature/device e.g. stm32f100?

**Comment by TheZoq2** [comment]
Unfortunately, there is not a fixed amount of ram for each chip family.

For example, the f103 has everything from 16k/6 to 1M/96k ram and flash

image

https://www.st.com/en/microcontrollers-microprocessors/stm32f103.html

**Comment by jaysonsantos** [comment]
Hey there, that makes sense.
I guess I will do it on my own build.rs.
Thanks!

**Pull request closed without merging**
