### PR TITLE
Impl multiplication and division for frequency wrappers

### PR DESCRIPTION
**Pull request by dbrgn**
This allows the following operations:

- T * u32 (T)
- T *= u32 (T)
- T / u32 (T)
- T /= u32 (T)
- T / T (u32)

It's implemented for the following types:

- Hertz
- KiloHertz
- MegaHertz
- Bps

### CODE REVIEW

**Comment by TheZoq2** [comment]
Sorry for the delay. Looks like a good change to me! Would you mind also adding an entry to CHANGELOG.md about it?

**Comment by therealprof** [comment]
Ping @dbrgn, any chance to getting the request @TheZoq2 addressed?

**Comment by dbrgn** [comment]
> Ping @dbrgn, any chance to getting the request @TheZoq2 addressed?

Yes, sure! Sorry, I somehow missed that comment.

PR is updated and rebased.

**Comment by TheZoq2** [comment]
Thanks!

**Pull request merged**
