### PR TITLE
Remove unnessecary unsafe blocks

### PR DESCRIPTION
**Pull request by TheZoq2**
As of the latest stm32f1 update, some unsafe blocks are no longer required this removes those. Since this just fixes compiler warnings, I very much doubt this will cause issues, but i'm making a PR for it just to be sure

### CODE REVIEW

**Comment by burrbull** [comment]
Some of `stm32-rs` patches were not applied for stm32f100

**Comment by TheZoq2** [comment]
Oh, I'm glad I made a PR then :P Is them not being applied a feature or will it be fixed soon?

**Comment by burrbull** [comment]
I'll see later what can be done.

More interesting question is what to do with digital v2?

**Comment by TheZoq2** [comment]
Yea, i'm not totally read up on digital v2. Have any of the other hals dealt with that yet?

**Comment by burrbull** [comment]
I've already tried to port this repo on `v2` but in this case old drivers don't work.

Maybe add `#![allow(deprecated)]` temporary?

**Comment by TheZoq2** [comment]
Yea, I think @therealprof also tried porting it at some point but ran into issues. Allowing deprecated might be our best option.

**Comment by geomatsi** [comment]
Hi @TheZoq2 

It turned out that recently stm32f4xx-hal has been updated: see https://github.com/stm32-rs/stm32f4xx-hal/pull/103. 

Maybe now this is time to do the same and break stm32f1xx-hal world as well ? :)
Let me know if it works for you. Then I will port f4 approach to f1 hal.

Regards,
Sergey

**Comment by burrbull** [comment]
@geomatsi Have you tested it with old drivers (v1)?

**Comment by TheZoq2** [comment]
I don't like breaking the world, but I guess if F4, F3 and L0 are doing it, we might as well. Or does @therealprof disagree?

**Comment by burrbull** [comment]
Here:
https://github.com/stm32-rs/stm32f4xx-hal/blob/2dfbe957ce07fdbbb5b3ea02cd67a3520d196855/src/gpio.rs#L161

you could do
```
self.is_set_low().map(|b| !b)
```
to avoid `unwrap`

**Comment by geomatsi** [comment]
Hi @burrbull 

No, I didn't. I don't have any stm32f4 pet project at the moment. There are compat layers in embedded-hal, including both v2 -> v1 and v1 -> v2. But I am not sure if they are going to work seamlessly w/o updating drivers.

**Comment by therealprof** [comment]
@TheZoq2 I try to be neutral on such a decision. This has caused me enough sweat and pain that I'd rather stay of any discussion.

**Comment by TheZoq2** [comment]
I read through the discussions surrounding this again, and from what I can tell, our current `v1` hal is compatible with `v2` drivers and applications without anyone changing anything, with the "minor" issue that we get a bunch of deprecation warnings.

While if we update to `v2`, we would break compatibility with all the `v1` consumers. Since our crate doesn't produce errors from digital things anyway, upgrading to `v2` doesn't seem to provide any benefit.

If the above is correct, i'd say the best approach is to stay on `v1` until more drivers and applications have migrated, at which point we would break less things with our upgrade.

**Comment by TeXitoi** [comment]
I thinks there is a v2 to v1 adapter that is moteur manual, something like into_v1, thus a hal v2 can be used with v1 drivers.

https://docs.rs/embedded-hal/0.2.3/embedded_hal/digital/v1_compat/index.html

**Comment by burrbull** [comment]
How to use this?

**Comment by TeXitoi** [comment]
I never tried and am in hollidays. I'll try to write an exemple without any promise.

**Comment by geomatsi** [comment]
Hi all,

I double-checked how it is done in [bitbang-hal](https://github.com/sajattack/bitbang-hal). It looks like v1/v2 gpio compat layer in embedded-hal indeed works seamlessly:
- embedded_hal::digital::v2 is directly imported in bitbang-hal and errors are handled, e.g. see i2c/spi implementation
- stm32f1xx-hal v1 gpio can be directly used with bitbang-hal w/o any intermediate layer, e.g. see [i2c example on stmf101](https://github.com/geomatsi/e.ziclean-cube/blob/master/examples/hal/example-hal-i2c-acc-test1.rs)

Regards,
Sergey

**Comment by TeXitoi** [comment]
v2 hal with v1 device mockup:

```rust
#![allow(deprecated)]

use embedded_hal::digital::{v1, v1_compat::OldOutputPin, v2};

struct Pin;

impl v2::OutputPin for Pin {
    type Error = ();
    fn set_low(&mut self) -> Result<(), Self::Error> {
        Ok(())
    }
    fn set_high(&mut self) -> Result<(), Self::Error> {
        Ok(())
    }
}

struct Device<P>(P);
impl<P: v1::OutputPin> Device<P> {
    fn new(pin: P) -> Device<P> {
        Device(pin)
    }
}

fn main() {
    let _device: Device<OldOutputPin<_>> = Device::new(Pin.into());
}
```

**Comment by TheZoq2** [comment]
I believe all unsafe warnings have been fixed with the upgrade to the f1 crate

**Pull request closed without merging**
