### PR TITLE
 replace Void with Infallible + small fixes

### PR DESCRIPTION
**Pull request by burrbull**
r? @therealprof

### CODE REVIEW

**Comment by TheZoq2** [comment]
Ohh, that's a neat feature. The change looks good to me, but the dependency on the void crate should probably be removed from `Cargo.toml`

**Comment by burrbull** [comment]
I could not remove it entirely due to https://github.com/rust-embedded/embedded-hal/blob/a5c0e3c63e4e431807d491d35dd67d1d43c07c92/src/timer.rs#L77

**Comment by TheZoq2** [comment]
Ah right, makes sense. I guess we might want to submit a PR to fix that in embedded-hal at some point.

**Comment by burrbull** [comment]
Yes. But in any case it will be breaking change.

**Comment by burrbull** [comment]
https://github.com/rust-embedded/embedded-hal/pull/150

**Comment by TheZoq2** [comment]
Do we want to merge this now, or wait for the embedded-hal PR to land?

**Comment by burrbull** [comment]
This part of changes shouldn't break user code (I hope).

**Comment by TheZoq2** [comment]
I think it will, we are changing public API after all.

For example, someone might have written wrapper functions around the GPIO pins like this
```rust
fn do_something_with_pins(...) -> Result<Something, Void> {
   pin.set_high()?; // ? Operator no longer works because return type changed from Void to Infallible
}
```

**Comment by burrbull** [comment]
Looks like you are right.
Have you seen this somewhere is used.

**Comment by TheZoq2** [comment]
No, I don't think I have. It also seems like kind of a weird thing to do if you understand the point of the Void type.

It might not make a difference though. We already have breaking changes staged for the next release, so we might as well throw this in. When embedded-hal updates, that too will be a breaking change (probably).

**Comment by TeXitoi** [comment]
Will break https://github.com/TeXitoi/blue-pill-quickstart/blob/master/src/main.rs#L42

**Comment by TheZoq2** [comment]
https://github.com/rust-lang/rust/pull/65355

Looks like the never type will be included in 1.40 :tada:. Do we still want to merge this, and then move to `!` or go straight to `!`? My vote is on the latter, as both things will be breaking changes

**Comment by burrbull** [comment]
By the way is there issue to disable `#[must_use]` check for `Result<smth, !>` to not write `.unwrap()` everywhere?

**Comment by TheZoq2** [comment]
That's a good question, it would certainly be nice

Also, I may have been too quick with my previous message. The comments on that rust-lang issue suggest that there is still some work to be done for it to stabilize.

**Comment by TheZoq2** [comment]
I submitted an issue here: https://github.com/rust-lang/rust/issues/65861

**Comment by therealprof** [comment]
> I don't mind "latest stable" at all, but perhaps someone else has concerns about it. @therealprof What do you think?

I would prefer to stay a couple of versions behind the latest and the greatest. `Infallible` is AFAIK planned to automatically turn into the never type as soon as supported by the compiler so switching to `Infallible` now seems like the right approach to me.

**Comment by burrbull** [comment]
Rebased

**Comment by TheZoq2** [comment]
Great! would you mind moving the changelog entry to the "Brekaing changes" section? Other than that, I think this is ready to be merged

**Comment by burrbull** [comment]
Done.

**Comment by TheZoq2** [comment]
Lovely, thanks!

**Pull request merged**
