### PR TITLE
public unsafe interface for rcc::Enable/Reset

### PR DESCRIPTION
**Pull request by burrbull**
https://riot.im/app/#/room/#rust-embedded:matrix.org/$hpsOhXJFao1S4JbCH6I_aEy2HFdqXy8f5XCb_d_711E

### CODE REVIEW

**Comment by TheZoq2** [comment]
Sorry for the delayed reply!

Did I understand the matrix discussion correctly in that this is supposed to be used for using devices that are not supported by the HAL?

If so, I think this looks reasonable, though it would be nice with a comment explaining the reason for this being unsafe, and what happens if you use it incorrectly.

**Comment by burrbull** [comment]
> Did I understand the matrix discussion correctly in that this is supposed to be used for using devices that are not supported by the HAL?

Yes, it is needed for alternative implementations and unsupported peripherals.

It's `unsafe` to indicate that user enable/disable peripheral at his own risk as it could break RCC safety abstraction.

**Comment by TheZoq2** [comment]
Sounds reasonable, though I think that should also be included in the docs for the function

**Comment by therealprof** [comment]
@burrbull Can you adjust the docs so we can get this landed?

**Comment by burrbull** [comment]
I never could write documentation.

**Comment by burrbull** [comment]
And I'm not sure about public interface.
Now it looks like this:
```rust
pub trait Enable {
    unsafe fn enable(apb: &mut Self::Bus);
    unsafe fn disable(apb: &mut Self::Bus);
}
pub trait Reset {
    unsafe fn reset(apb: &mut Self::Bus);
}
```

As these functions are `unsafe` maybe it make sense to simplify it to just:
```rust
pub trait Enable {
    unsafe fn enable();
    unsafe fn disable();
}
pub trait Reset {
    unsafe fn reset();
}
```
and implement for each peripheral?

**Comment by burrbull** [comment]
Or I can split these PR on 2.

**Pull request closed without merging**
