### PR TITLE
RCC Bus

### PR DESCRIPTION
**Pull request by burrbull**
It is not breaking change.

### CODE REVIEW

**Comment by burrbull** [comment]
cc @TheZoq2 
cc @therealprof

**Comment by burrbull** [comment]
Done.

**Comment by therealprof** [comment]
@TheZoq2 Would you mind lending me another pair of eyes here?

**Comment by TheZoq2** [comment]
Sure, I'll have a look at it after work in a few hours

**Comment by burrbull** [comment]
ping @TheZoq2

**Pull request merged**
