### PR TITLE
Proposal for setting the IO Slew Rate

### LINKED ISSUE #266: Set IO Slew Rate
The HAL Currently lacks the ability to set the IO slew rate, and always sets the maximum slew rate initially

### PR DESCRIPTION
**Pull request by electroCutie**
Fixes #266 by adding an enumeration of IO speeds available and a single method trait that is implemented for Output pins as well as push-pull alternate function pins

### CODE REVIEW

**Comment by TheZoq2** [comment]
Thanks for the PR!

I feel like it would be nice to have more descriptive names as slow/medium/fast could really be anything. I can't come up with a very good suggestion though

Perhaps `Mhz20` `Mhz10`...

Also, would you mind adding a changelog entry? :)

**Comment by electroCutie** [comment]
> Also, would you mind adding a changelog entry? :)

 @TheZoq2 I wasn't sure what to do about the version number for the changelog entry. Any tips for something like this?

> Perhaps Mhz20 Mhz10...

Yeah, I'll give it some thought and rename them

**Comment by electroCutie** [comment]
@TheZoq2 okay, done

**Comment by TheZoq2** [comment]
Awesme, thanks. Changelog entry looks perfect as well!

**Pull request merged**
