### PR TITLE
Improve README

### PR DESCRIPTION
**Pull request by TheZoq2**
Followup to #37 which improves the README.

- Add badges for docs.rs and crates.io
- Add example code
- Some wording and stylistic changes
- Prevent line wrap in docs code sample

I also moved the example usage instructions from lib.rs to README because I feel like they are more relevant here. I go to docs.rs when i've added the crate as a dependency and want to use it and to the repo when I first encounter the crate which is when i'd want to run the examples.

I kind of feel like the blinky example is a bit out of place, but I also like having some sort of code sample in the README...

### CODE REVIEW

**Comment by TheZoq2** [comment]
Yes, a release would be nice, did you end up giving me publish access on crates, if so I can take care of it

**Comment by therealprof** [comment]
I thought so, I vaguely remember looking up how that works and it was surprisingly straight forward. ;)

... was probably some other crate, though. You should have received an invitation about now.

**Comment by TheZoq2** [comment]
Yep, looks like crates doesn't send any sort of notification unless you log in and click owner invites, thanks

**Comment by TheZoq2** [comment]
v0.2.1 has been released :tada: Hopefully I did everything correctly :)

**Comment by therealprof** [comment]
@TheZoq2 Looking good! Thanks.

**Pull request merged**
