### PR TITLE
Edition 2018

### LINKED ISSUE #16: Exporting the sdv2rust crate as device
For consistency, I propose to re export the sdv2rust crate as `device`. It is coherent with the name used by RTFM: https://japaric.github.io/cortex-m-rtfm/book/by-example/app.html

If there is approvals and no veto, I can propose such a PR.

### PR DESCRIPTION
**Pull request by burrbull**
2018 edition path style.

Closes #16 .

### CODE REVIEW

**Comment by TheZoq2** [comment]
Thanks for the PR, this is definitely a good idea.

The changes look good to me, but the examples also have to be updated to the new edition, would you be able to do that?

Also, I don't think we came to a conclusion about what name to use for the "pac" crate in #16 . Perhaps we should stick with stm32 until there is an "official" conclusion as we would otherwise have 2 breaking changes.

**Comment by burrbull** [comment]
As you can see, I've exported all three (`stm32`, `device` and `pac`) names. I prefer `device`, but `pac` is shorter.

**Comment by TheZoq2** [comment]
Ah right, I missed that. In that case, the PR looks good apart from the missing examples

**Comment by burrbull** [comment]
I am working on examples.

**Comment by burrbull** [comment]
Done.

**Comment by TheZoq2** [comment]
Looks almost perfect, though I do have some questions:

- Why did you replace `panic_semihosting` with `panic_halt`, i'm fine with either but I am curious
- What does the panic example show? The description and code look like it just shows printing hello world, but then the name panic doesn't make sense

**Comment by burrbull** [comment]
I think examples should be as clean as possible. So I deleted panic handlers from most of examples and created additional example with panic illustration. Furthermore semihosting works only with debugger.

**Comment by therealprof** [comment]
@burrbull I agree. Thanks for caring about the details.

**Comment by TheZoq2** [comment]
Sounds reasonable, I'd say this is ready to merge then. Thanks for the help!

**Pull request merged**
